// Curated starter dictionary (EN→AR) for the built-in CEFR word lists.
// Notes:
// - Keys must be UPPERCASE English words (already normalized).
// - Values can be Arabic with/without spaces; normalization in the API will strip spaces/harakat.

export const DICT_A1_A2: Record<string, string> = {
  FAMILY: 'عائلة',
  FRIEND: 'صديق',
  SCHOOL: 'مدرسة',
  TEACHER: 'معلم',
  STUDENT: 'طالب',
  BOOK: 'كتاب',
  PEN: 'قلم',
  PAPER: 'ورق',
  PHONE: 'هاتف',
  COMPUTER: 'كمبيوتر',
  MUSIC: 'موسيقى',
  MOVIE: 'فيلم',
  FOOD: 'طعام',
  WATER: 'ماء',
  COFFEE: 'قهوة',
  TEA: 'شاي',
  BREAD: 'خبز',
  RICE: 'أرز',
  FRUIT: 'فاكهة',
  APPLE: 'تفاح',
  BANANA: 'موز',
  ORANGE: 'برتقال',
  VEGETABLE: 'خضار',
  MEAT: 'لحم',
  FISH: 'سمك',
  MILK: 'حليب',
  CHEESE: 'جبن',
  EGG: 'بيض',
  SUGAR: 'سكر',
  SALT: 'ملح',
  CITY: 'مدينة',
  STREET: 'شارع',
  HOUSE: 'بيت',
  HOME: 'منزل',
  ROOM: 'غرفة',
  DOOR: 'باب',
  WINDOW: 'نافذة',
  CAR: 'سيارة',
  BUS: 'حافلة',
  TRAIN: 'قطار',
  AIRPORT: 'مطار',
  HOTEL: 'فندق',
  MARKET: 'سوق',
  SHOP: 'متجر',
  MONEY: 'مال',
  PRICE: 'سعر',
  TODAY: 'اليوم',
  TOMORROW: 'غداً',
  YESTERDAY: 'أمس',
  MORNING: 'صباح',
  EVENING: 'مساء',
  NIGHT: 'ليل',
  WEEK: 'أسبوع',
  MONTH: 'شهر',
  YEAR: 'سنة',
  HAPPY: 'سعيد',
  SAD: 'حزين',
  TIRED: 'متعب',
  HUNGRY: 'جائع',
  THIRSTY: 'عطشان',
  HOT: 'حار',
  COLD: 'بارد',
  BIG: 'كبير',
  SMALL: 'صغير',
  GOOD: 'جيد',
  BAD: 'سيئ',
  NEW: 'جديد',
  OLD: 'قديم',
  FAST: 'سريع',
  SLOW: 'بطيء',
  RIGHT: 'يمين',
  LEFT: 'يسار',
  OPEN: 'افتح',
  CLOSE: 'أغلق',
  START: 'ابدأ',
  STOP: 'توقف',
  WORK: 'عمل',
  STUDY: 'يدرس',
  READ: 'يقرأ',
  WRITE: 'يكتب',
  SPEAK: 'يتكلم',
  LISTEN: 'يستمع',
  WALK: 'يمشي',
  RUN: 'يجري',
};

// For now, intermediate/advanced are empty; we can grow these over time.
export const DICT_B1_B2: Record<string, string> = {};
export const DICT_C1_C2: Record<string, string> = {};
