// Generated by npm run dictionary:batch006. Typed immutable review overlay; do not edit.
import type { DictionaryHeadword } from './dictionary.js';
import { DICTIONARY_BATCH006 as source } from './dictionary.stage3b.batch006.generated.js';
const updates = new Map<number, DictionaryHeadword>([
[5072, ({
  "english": "INVITE",
  "translations": [
    {
      "arabic": "دعوة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "الدعوة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword]
]);
export const DICTIONARY_BATCH006_QA: DictionaryHeadword[] = source.map((headword,index)=>updates.get(index)??headword);
