// Generated by npm run dictionary:batch006. Typed immutable review overlay; do not edit.
import type { DictionaryHeadword } from './dictionary.js';
import { DICTIONARY_BATCH005_QA as source } from './dictionary.stage3b.batch005.qa.generated.js';
const updates = new Map<number, DictionaryHeadword>([
[2487, ({
  "english": "OFFICIALS",
  "translations": [
    {
      "arabic": "مسؤولين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "المسؤولين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "المسؤولون",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2524, ({
  "english": "NOTED",
  "translations": [
    {
      "arabic": "لوحظ",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "ملاحظة",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2541, ({
  "english": "HELPS",
  "translations": [
    {
      "arabic": "يساعد",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2586, ({
  "english": "COLOUR",
  "translations": [
    {
      "arabic": "لون",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "اللون",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2590, ({
  "english": "UTILITIES",
  "translations": [
    {
      "arabic": "المرافق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "مرافق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "المنافع",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "المرافق العامة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2847, ({
  "english": "EURO",
  "translations": [
    {
      "arabic": "يورو",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "اليورو",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "باليورو",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2872, ({
  "english": "ANGEL",
  "translations": [
    {
      "arabic": "الملاك",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "ملاك",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "انجيل",
      "status": "rejected",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": false,
      "allowedForArToEn": false,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "انجل",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun",
      "allowedForEnToAr": false,
      "allowedForArToEn": false,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[2964, ({
  "english": "INSTITUTION",
  "translations": [
    {
      "arabic": "مؤسسة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "المؤسسة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[3108, ({
  "english": "ATTRACTIONS",
  "translations": [
    {
      "arabic": "الجذب",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "مناطق الجذب السياحي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[3719, ({
  "english": "OPERATE",
  "translations": [
    {
      "arabic": "تشغيل",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[3777, ({
  "english": "ORGANISATIONS",
  "translations": [
    {
      "arabic": "منظمات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "المنظمات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[3949, ({
  "english": "EAGLE",
  "translations": [
    {
      "arabic": "النسر",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "نسر",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4074, ({
  "english": "DONATE",
  "translations": [
    {
      "arabic": "تبرع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "التبرع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4100, ({
  "english": "DOSE",
  "translations": [
    {
      "arabic": "الجرعة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "جرعة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4112, ({
  "english": "SHAVED",
  "translations": [
    {
      "arabic": "حلقت",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "حليق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4313, ({
  "english": "CLOSELY",
  "translations": [
    {
      "arabic": "عن كثب",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adverb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4371, ({
  "english": "YOGA",
  "translations": [
    {
      "arabic": "اليوغا",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "يوغا",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "اليوجا",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4419, ({
  "english": "INSTITUTIONAL",
  "translations": [
    {
      "arabic": "مؤسسية",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "المؤسسية",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4433, ({
  "english": "PLENTY",
  "translations": [
    {
      "arabic": "الكثير",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4434, ({
  "english": "SOLO",
  "translations": [
    {
      "arabic": "سولو",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "فردي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "منفردة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "منفرد",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "منفردا",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adverb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4502, ({
  "english": "OPENS",
  "translations": [
    {
      "arabic": "يفتح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4528, ({
  "english": "EASE",
  "translations": [
    {
      "arabic": "سهولة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4611, ({
  "english": "LOCATE",
  "translations": [
    {
      "arabic": "حدد موقع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4680, ({
  "english": "ODDS",
  "translations": [
    {
      "arabic": "الاحتمالات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "احتمالات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4852, ({
  "english": "MINT",
  "translations": [
    {
      "arabic": "نعناع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "منت",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun",
      "allowedForEnToAr": false,
      "allowedForArToEn": false,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "النعناع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4899, ({
  "english": "LOOSE",
  "translations": [
    {
      "arabic": "طليق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "فضفاضة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4905, ({
  "english": "EARNED",
  "translations": [
    {
      "arabic": "كسبت",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "المكتسبات",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[4995, ({
  "english": "ATLAS",
  "translations": [
    {
      "arabic": "اطلس",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "الأطلس",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5033, ({
  "english": "ANTENNA",
  "translations": [
    {
      "arabic": "الهوائي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "هوائي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5072, ({
  "english": "INVITE",
  "translations": [
    {
      "arabic": "دعوة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "الدعوة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5312, ({
  "english": "TWELVE",
  "translations": [
    {
      "arabic": "اثنا عشر",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "determiner",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5583, ({
  "english": "ALIEN",
  "translations": [
    {
      "arabic": "اجنبي",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "الاجنبي",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "فضائي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true,
      "sense": "extraterrestrial"
    },
    {
      "arabic": "أجنبي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true,
      "sense": "foreign"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5609, ({
  "english": "DISCS",
  "translations": [
    {
      "arabic": "الاقراص",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "الأقراص المضغوطة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false,
      "sense": "compact discs"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5632, ({
  "english": "AFFORD",
  "translations": [
    {
      "arabic": "تحمل",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "verb"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5644, ({
  "english": "INCLUSION",
  "translations": [
    {
      "arabic": "الشمول",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "تضمين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "ادراج",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "إدراج",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5672, ({
  "english": "AUTHENTIC",
  "translations": [
    {
      "arabic": "الاصيل",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "اصيلة",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "اصيل",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "اصلية",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "أصلي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5684, ({
  "english": "RANGING",
  "translations": [
    {
      "arabic": "تتراوح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5764, ({
  "english": "RESET",
  "translations": [
    {
      "arabic": "استرجع",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "verb"
    },
    {
      "arabic": "إعادة تعيين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[5776, ({
  "english": "TONGUE",
  "translations": [
    {
      "arabic": "لسان",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "اللسان",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6013, ({
  "english": "ASSESSMENTS",
  "translations": [
    {
      "arabic": "التقييمات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6077, ({
  "english": "DEMONSTRATION",
  "translations": [
    {
      "arabic": "مظاهرة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "المظاهرة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6190, ({
  "english": "RIPE",
  "translations": [
    {
      "arabic": "ناضج",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6316, ({
  "english": "EASTER",
  "translations": [
    {
      "arabic": "الفصح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "عيد الفصح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6319, ({
  "english": "PRAISE",
  "translations": [
    {
      "arabic": "الثناء",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "سبحان",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "ماشاء",
      "status": "rejected",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": false,
      "allowedForArToEn": false,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "الحمد",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6356, ({
  "english": "MODIFICATIONS",
  "translations": [
    {
      "arabic": "تعديلات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "التعديلات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6358, ({
  "english": "PIXEL",
  "translations": [
    {
      "arabic": "بيكسل",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "بكسل",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6489, ({
  "english": "PRACTITIONERS",
  "translations": [
    {
      "arabic": "الممارسين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "الممارسون",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6553, ({
  "english": "ANNEX",
  "translations": [
    {
      "arabic": "المرفق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "مرفق",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6564, ({
  "english": "DOWNLOADING",
  "translations": [
    {
      "arabic": "تنزيل",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "تحميل",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6575, ({
  "english": "KNEE",
  "translations": [
    {
      "arabic": "الركبة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "ركبة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6599, ({
  "english": "TECHNO",
  "translations": [
    {
      "arabic": "كنو",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "تكنو",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6631, ({
  "english": "ADVISE",
  "translations": [
    {
      "arabic": "تقديم المشورة",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6735, ({
  "english": "INTAKE",
  "translations": [
    {
      "arabic": "المدخول",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6824, ({
  "english": "RETRO",
  "translations": [
    {
      "arabic": "الرجعية",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "رجعي",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "adjective"
    },
    {
      "arabic": "ريترو",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "adjective"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6980, ({
  "english": "ARRANGE",
  "translations": [
    {
      "arabic": "ترتيب",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[6997, ({
  "english": "NOTIFICATIONS",
  "translations": [
    {
      "arabic": "إخطارات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[7053, ({
  "english": "BEANS",
  "translations": [
    {
      "arabic": "الفاصولياء",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "الفول",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false,
      "sense": "broad beans"
    },
    {
      "arabic": "الفاصوليا",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "فول",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false,
      "sense": "broad beans"
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[7323, ({
  "english": "TRIO",
  "translations": [
    {
      "arabic": "الثلاثي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "ثلاثي",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[7485, ({
  "english": "DIETARY",
  "translations": [
    {
      "arabic": "الغذائية",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "adjective",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[7499, ({
  "english": "SPEEDS",
  "translations": [
    {
      "arabic": "السرعات",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[7636, ({
  "english": "MESA",
  "translations": [
    {
      "arabic": "ميسا",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun"
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[8123, ({
  "english": "UNDO",
  "translations": [
    {
      "arabic": "تراجع",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[8509, ({
  "english": "YEN",
  "translations": [
    {
      "arabic": "ين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "يين",
      "status": "review",
      "register": "msa",
      "partOfSpeech": "noun"
    },
    {
      "arabic": "الين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[8798, ({
  "english": "LANCE",
  "translations": [
    {
      "arabic": "لانس",
      "status": "review",
      "register": "uncertain",
      "partOfSpeech": "noun",
      "allowedForEnToAr": false,
      "allowedForArToEn": false,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "review",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[8883, ({
  "english": "MONITORED",
  "translations": [
    {
      "arabic": "رصدت",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "verb",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[9080, ({
  "english": "COMMISSIONERS",
  "translations": [
    {
      "arabic": "المفوضين",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    },
    {
      "arabic": "المفوضون",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword],
[9232, ({
  "english": "MUG",
  "translations": [
    {
      "arabic": "قدح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": true,
      "preferredForArToEn": true
    },
    {
      "arabic": "القدح",
      "status": "approved",
      "register": "msa",
      "partOfSpeech": "noun",
      "allowedForEnToAr": true,
      "allowedForArToEn": true,
      "preferredForEnToAr": false,
      "preferredForArToEn": false
    }
  ],
  "status": "approved",
  "cefr": null
} satisfies DictionaryHeadword) as DictionaryHeadword]
]);
export const DICTIONARY_BATCH006: DictionaryHeadword[] = source.map((headword,index)=>updates.get(index)??headword);
