import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { DICTIONARY } from '../api/_lib/dictionary.generated.ts';
import { DICTIONARY_STAGE2 } from '../api/_lib/dictionary.stage2.generated.ts';
import { DICT_COMMON_3000_ABBREV } from '../api/dict_common_3000_abbrev.ts';
import { eligibleTranslation } from '../api/_lib/dictionary.ts';
import { cleanupStage2 } from './stage2.ts';
import { applyStage3a, reviewCsv } from './stage3a.ts';

const root = new URL('../dictionary/stage3a/', import.meta.url);
const stage2 = cleanupStage2(DICTIONARY, new Set(Object.keys(DICT_COMMON_3000_ABBREV)));
if (JSON.stringify(stage2.dictionary) !== JSON.stringify(DICTIONARY_STAGE2)) throw new Error('Stage 2 snapshot drift');
const manifest = JSON.parse(readFileSync(new URL('decisions.json', root), 'utf8'));
const result = applyStage3a(stage2, manifest);
const group = (rows: Record<string, unknown>[], field: string) => rows.reduce<Record<string, number>>((counts, row) => { const key = String(row[field]); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {});
const counts = (dictionary: typeof result.dictionary) => {
  const relationships = dictionary.flatMap(h => h.translations);
  return { headwords: dictionary.length, relationships: relationships.length,
    headwordStatus: group(dictionary, 'status'), relationshipStatus: group(relationships, 'status'), register: group(relationships, 'register'),
    multiwordDisplays: relationships.filter(t => t.arabic.trim().split(/\s+/).length > 1).length,
    compatibilityEligible: dictionary.reduce((n,h) => n + h.translations.filter(t => eligibleTranslation(h,t,'compatibility')).length,0),
    strictApprovedEligible: dictionary.reduce((n,h) => n + h.translations.filter(t => eligibleTranslation(h,t,'approved-only')).length,0),
  };
};
const hash = (url: URL) => createHash('sha256').update(readFileSync(url)).digest('hex');
const report = {
  sourceSha256: hash(new URL('../api/_lib/dictionary.stage2.generated.ts',import.meta.url)),
  decisionsSha256: hash(new URL('decisions.json',root)), before: counts(DICTIONARY_STAGE2), after: counts(result.dictionary),
  reviewedRelationships: result.decisions.length, reviewedHeadwords: new Set(result.decisions.map(d=>d.english)).size,
  untouchedRelationships: DICTIONARY_STAGE2.reduce((n,h)=>n+h.translations.length,0)-result.decisions.length,
  decisionStatus: group(result.decisions,'status'), decisionConfidence: group(result.decisions,'confidence'),
  reviewedCategories: Object.fromEntries([...new Set(result.decisions.flatMap(d=>d.categories))].map(c=>[c,result.decisions.filter(d=>d.categories.includes(c)).length])),
  reviewedCategoryHeadwords: Object.fromEntries([...new Set(result.decisions.flatMap(d=>d.categories))].map(c=>[c,new Set(result.decisions.filter(d=>d.categories.includes(c)).map(d=>d.english)).size])),
  appliedTextCorrections: result.decisions.filter(d=>d.applied).length,
  proposedUnapplied: result.decisions.filter(d=>d.proposedReplacement !== null && !d.applied).length,
  metadataChanges: result.decisions.filter(d=>d.metadataChanged).length,
  correctedByReason: group(result.decisions.filter(d=>d.applied),'reasonCode'),
  rejectedByReason: group(result.decisions.filter(d=>d.status==='rejected'),'reasonCode'),
  unresolvedByReason: group(result.decisions.filter(d=>d.status==='review'),'reasonCode'),
  headwordActions: result.headwordActions,
  deletedRelationships: 0, newRelationships: 0, cefrAssignments: 0,
};
const outputs = new Map<URL,string>([
  [new URL('../api/_lib/dictionary.stage3a.generated.ts',import.meta.url), '// Generated by npm run dictionary:review3a from frozen Stage 2 and explicit decisions.\n' + "import type { DictionaryHeadword } from './dictionary.js';\n" + 'export const DICTIONARY_STAGE3A: DictionaryHeadword[] = ' + JSON.stringify(result.dictionary,null,2)+';\n'],
  [new URL('report.json',root),JSON.stringify(report,null,2)+'\n'],
  [new URL('decisions.csv',root),reviewCsv(result.decisions)],
  [new URL('corrected.csv',root),reviewCsv(result.decisions.filter(d=>d.applied))],
  [new URL('rejected.csv',root),reviewCsv(result.decisions.filter(d=>d.status==='rejected'))],
  [new URL('unresolved.csv',root),reviewCsv(result.decisions.filter(d=>d.status==='review'))],
  [new URL('headwords.csv',root),reviewCsv(result.headwordActions)],
]);
if(process.argv[2]==='generate') { mkdirSync(root,{recursive:true}); for(const [url,content] of outputs)writeFileSync(url,content); }
else if(process.argv[2]==='audit') { for(const [url,content] of outputs)if(readFileSync(url,'utf8')!==content)throw new Error(`Stage 3A output drift: ${url.pathname}`); }
else throw new Error('Use generate or audit');
const {headwordActions,...summary}=report;
console.info(JSON.stringify({...summary,headwordStatusChanges:headwordActions.length},null,2));
