import { writeFileSync, mkdirSync } from 'node:fs';
import { DICT_COMMON_30000_NON_EMPTY as raw } from '../api/DICT_COMMON_30000_non_empty.ts';
import { DICT_COMMON_3000_ABBREV as abbreviations } from '../api/dict_common_3000_abbrev.ts';
import { migrate, audit, equivalenceFailures } from './dictionary-tools.ts';

const command = process.argv[2];
if (command === 'migrate') {
  const dictionary = migrate(raw);
  const failures = equivalenceFailures(raw, dictionary);
  if (failures.length) {
    console.error(JSON.stringify(failures, null, 2));
    process.exitCode = 1; // Never overwrite the production dictionary on failure.
  } else {
    writeFileSync(new URL('../api/_lib/dictionary.generated.ts', import.meta.url),
      '// Generated by npm run dictionary:migrate. Raw source is preserved; do not edit manually.\n' +
      "import type { DictionaryHeadword } from './dictionary.js';\n" +
      'export const DICTIONARY: DictionaryHeadword[] = ' + JSON.stringify(dictionary, null, 2) + ';\n');
    console.info(`Migrated ${dictionary.length} headwords / ${dictionary.reduce((n, h) => n + h.translations.length, 0)} relationships; zero equivalence failures.`);
  }
} else if (command === 'audit') {
  const { DICTIONARY } = await import('../api/_lib/dictionary.generated.ts');
  const result = audit(raw, DICTIONARY, abbreviations);
  mkdirSync(new URL('../dictionary/', import.meta.url), { recursive: true });
  writeFileSync(new URL('../dictionary/audit.json', import.meta.url), JSON.stringify(result, null, 2) + '\n');
  const { review, sharedArabic, abbreviationHeadwords, ...summary } = result;
  console.info(JSON.stringify({ ...summary, abbreviationHeadwords: abbreviationHeadwords.length,
    reviewExamples: review.slice(0, 10), sharedArabicExamples: sharedArabic.slice(0, 3) }, null, 2));
  if (result.equivalenceFailures.length) process.exitCode = 1;
} else {
  throw new Error('Use dictionary:migrate or dictionary:audit');
}
