import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { DICTIONARY as source } from '../api/_lib/dictionary.generated.ts';
import { DICT_COMMON_3000_ABBREV } from '../api/dict_common_3000_abbrev.ts';
import { eligibleTranslation } from '../api/_lib/dictionary.ts';
import { cleanupStage2, verifyStage2, csv } from './stage2.ts';

const result = cleanupStage2(source, new Set(Object.keys(DICT_COMMON_3000_ABBREV)));
const failures = verifyStage2(source, result);
if (failures.length) throw new Error(JSON.stringify(failures));
const output = new URL('../dictionary/stage2/', import.meta.url);
const production = new URL('../api/_lib/dictionary.stage2.generated.ts', import.meta.url);
const content = '// Generated by npm run dictionary:cleanup. Source: dictionary.generated.ts (preserved).\n' +
  "import type { DictionaryHeadword } from './dictionary.js';\n" +
  'export const DICTIONARY_STAGE2: DictionaryHeadword[] = ' + JSON.stringify(result.dictionary, null, 2) + ';\n';
const countStatus = (items: { status?: string }[]) => Object.fromEntries(['approved', 'review', 'rejected', 'unset'].map(s => [s, items.filter(i => (i.status ?? 'unset') === s).length]));
const translations = result.dictionary.flatMap(h => h.translations);
const category = (name: string) => result.review.filter(r => r.category === name).length;
const uniqueEnglish = (names: string[]) => new Set(result.review.filter(r => names.includes(r.category)).map(r => r.english)).size;
const eligible = (policy: 'compatibility' | 'approved-only') => ({
  headwords: result.dictionary.filter(h => h.translations.some(t => eligibleTranslation(h, t, policy))).length,
  relationships: result.dictionary.reduce((n, h) => n + h.translations.filter(t => eligibleTranslation(h, t, policy)).length, 0),
});
const metrics = {
  sourceHeadwords: source.length, sourceRelationships: source.reduce((n, h) => n + h.translations.length, 0),
  headwords: result.dictionary.length, relationships: translations.length, preservationFailures: failures,
  headwordStatus: countStatus(result.dictionary), relationshipStatus: countStatus(translations),
  register: Object.fromEntries(['msa','dialect','uncertain'].map(s => [s, translations.filter(t => t.register === s).length])),
  duplicateRelationshipsConsolidated: result.consolidations.length,
  repeatedWordReviews: category('repeated-word'),
  abbreviationCandidates: result.abbreviations.length,
  abbreviationClasses: Object.fromEntries(['clear abbreviation/acronym','likely normal word','uncertain'].map(c => [c, result.abbreviations.filter(a => a.category === c).length])),
  properNameCandidates: uniqueEnglish(['proper-name']), brandPlaceCandidates: uniqueEnglish(['brand-name','place-name']),
  suspiciousTransliterations: category('transliteration'), articleVariantGroups: category('article-variant'),
  multiwordTranslations: translations.filter(t => t.arabic.trim().split(/\s+/).length > 1).length,
  multipleMeaningHeadwords: category('multiple-meanings'), directionAmbiguityGroups: category('direction-ambiguity'),
  latinInArabic: category('latin-in-arabic'), noisyEnglishHeadwords: uniqueEnglish(['noisy-english']),
  over13Cells: category('over-13-cells'), editorialNotes: category('editorial-note'), possiblyMalformed: category('possibly-malformed'),
  possibleDialectReviews: category('possible-dialect'),
  queues: Object.fromEntries([1,2,3].map(p => [p, result.review.filter(r => r.priority === p).length])),
  metadataActions: result.metadataActions.length, displayRewrites: 0, cefrAssignments: 0,
  compatibility: eligible('compatibility'), strictApprovedOnly: eligible('approved-only'),
};
const hash = (url: URL) => createHash('sha256').update(readFileSync(url)).digest('hex');
const report = { sourceSha256: hash(new URL('../api/_lib/dictionary.generated.ts', import.meta.url)),
  rulesSha256: hash(new URL('./stage2-rules.ts', import.meta.url)), metrics,
  consolidations: result.consolidations, metadataActions: result.metadataActions,
  lineage: result.lineage, abbreviations: result.abbreviations };
if (process.argv[2] === 'generate') {
  mkdirSync(output, { recursive: true });
  writeFileSync(production, content);
  writeFileSync(new URL('report.json', output), JSON.stringify(report, null, 2) + '\n');
  for (const p of [1,2,3]) writeFileSync(new URL(`priority-${p}.csv`, output), csv(result.review.filter(r => r.priority === p)));
} else if (process.argv[2] === 'audit') {
  if (readFileSync(production, 'utf8') !== content) throw new Error('Stage 2 production data differs from deterministic regeneration. Run dictionary:cleanup and review changes.');
  if (readFileSync(new URL('report.json', output), 'utf8') !== JSON.stringify(report, null, 2) + '\n') throw new Error('Stage 2 report differs from regeneration');
  for (const p of [1,2,3]) if (readFileSync(new URL(`priority-${p}.csv`, output), 'utf8') !== csv(result.review.filter(r => r.priority === p))) throw new Error(`Priority ${p} queue differs from regeneration`);
} else throw new Error('Use generate or audit');
console.info(JSON.stringify(metrics, null, 2));
